/*
 * Google Earth Engine Script: OLCI Sargassum Detection
 * 
 * Computes AFAI and MCI indices from Sentinel-3 OLCI data for Ghana offshore band.
 * Exports rasters and detection centroids to Google Cloud Storage.
 * 
 * Usage:
 * 1. Set parameters at top of script
 * 2. Run in GEE Code Editor
 * 3. Check Map for visual QA
 * 4. Export tasks will be created automatically
 */

// ========================================
// CONFIGURATION PARAMETERS
// ========================================

// Date parameters
var TARGET_DATE = '2025-10-12';  // YYYY-MM-DD format
var DATE_RANGE_DAYS = 1;         // Days around target date

// Detection thresholds
var AFAI_THRESHOLD = 0.02;       // AFAI threshold for Sargassum detection
var MCI_THRESHOLD = 0.00;        // MCI threshold for Sargassum detection

// Export parameters
var GCS_BUCKET = 'YOUR_BUCKET_NAME';  // TODO: Replace with your GCS bucket
var EXPORT_SCALE = 300;               // Export resolution in meters (OLCI native ~300m)

// Ghana offshore band (0-20 nautical miles)
// This should match the ROI generated by scripts/build_roi.py
var GHANA_BOUNDS = ee.Geometry.Rectangle([-4.5, 3.0, 2.5, 7.0]);

// ========================================
// HELPER FUNCTIONS
// ========================================

/**
 * Create Ghana 0-20nm offshore band server-side
 * This approximates the ROI created by build_roi.py
 */
function createGhanaOffshoreBand() {
  // Get Ghana country boundary
  var countries = ee.FeatureCollection('USDOS/LSIB_SIMPLE/2017');
  var ghana = countries.filter(ee.Filter.eq('country_na', 'Ghana'));
  
  // Buffer Ghana by 20 nautical miles (37.04 km)
  var ghanaBuffered = ghana.geometry().buffer(37040, 100); // 100m tolerance for geodesic
  
  // Subtract original Ghana to get offshore band
  var offshoreBand = ghanaBuffered.difference(ghana.geometry());
  
  // Clip to reasonable bounds
  return offshoreBand.intersection(GHANA_BOUNDS);
}

/**
 * Apply quality mask to OLCI data
 */
function applyQualityMask(image) {
  // Get quality flags if available
  var qualityFlags = image.select(['quality_flags'], ['quality']).toInt();
  
  // Basic quality mask (adjust based on OLCI QC documentation)
  // Remove clouds, glint, and suspicious pixels
  var cloudMask = qualityFlags.bitwiseAnd(Math.pow(2, 18)).eq(0); // CLOUD
  var glintMask = qualityFlags.bitwiseAnd(Math.pow(2, 21)).eq(0); // GLINT_RISK
  var suspiciousMask = qualityFlags.bitwiseAnd(Math.pow(2, 24)).eq(0); // AC_FAIL
  
  var qualityMask = cloudMask.and(glintMask).and(suspiciousMask);
  
  // Also mask negative and extreme Rrs values
  var rrs665 = image.select('Rrs_665');
  var rrs681 = image.select('Rrs_681');
  var rrs709 = image.select('Rrs_709');
  var rrs754 = image.select('Rrs_754');
  var rrs865 = image.select('Rrs_865');
  var rrs1020 = image.select('Rrs_1020');
  
  // Mask negative and extreme values
  var validMask = rrs665.gt(0).and(rrs665.lt(0.1))
                  .and(rrs681.gt(0)).and(rrs681.lt(0.1))
                  .and(rrs709.gt(0)).and(rrs709.lt(0.1))
                  .and(rrs754.gt(0)).and(rrs754.lt(0.1))
                  .and(rrs865.gt(0)).and(rrs865.lt(0.1))
                  .and(rrs1020.gt(0)).and(rrs1020.lt(0.1));
  
  var finalMask = qualityMask.and(validMask);
  
  return image.updateMask(finalMask);
}

/**
 * Compute AFAI (Alternative Floating Algae Index)
 */
function computeAFAI(image) {
  var rrs665 = image.select('Rrs_665');
  var rrs865 = image.select('Rrs_865');
  var rrs1020 = image.select('Rrs_1020');
  
  // AFAI = Rrs_865 - [Rrs_665 + (Rrs_1020 - Rrs_665) * (865-665)/(1020-665)]
  var baseline = rrs665.add(
    rrs1020.subtract(rrs665).multiply((865 - 665) / (1020 - 665))
  );
  
  var afai = rrs865.subtract(baseline);
  
  return afai.rename('afai');
}

/**
 * Compute MCI (Maximum Chlorophyll Index)
 */
function computeMCI(image) {
  var rrs681 = image.select('Rrs_681');
  var rrs709 = image.select('Rrs_709');
  var rrs754 = image.select('Rrs_754');
  
  // MCI = Rrs_709 - [Rrs_681 + (Rrs_754 - Rrs_681) * (709-681)/(754-681)]
  var baseline = rrs681.add(
    rrs754.subtract(rrs681).multiply((709 - 681) / (754 - 681))
  );
  
  var mci = rrs709.subtract(baseline);
  
  return mci.rename('mci');
}

// ========================================
// MAIN PROCESSING
// ========================================

print('Starting OLCI Sargassum detection for', TARGET_DATE);

// Create ROI
var roi = createGhanaOffshoreBand();
print('Created Ghana offshore band ROI');

// Define date range
var startDate = ee.Date(TARGET_DATE);
var endDate = startDate.advance(DATE_RANGE_DAYS, 'day');

print('Date range:', startDate.format('YYYY-MM-dd'), 'to', endDate.format('YYYY-MM-dd'));

// Load OLCI collection
var olciCollection = ee.ImageCollection('COPERNICUS/S3/OLCI/OL_2_WFR')
  .filterDate(startDate, endDate)
  .filterBounds(roi)
  .map(applyQualityMask);

print('OLCI collection size:', olciCollection.size());

// Check if we have data
var hasData = olciCollection.size().gt(0);
print('Has OLCI data:', hasData);

// Process if data available
var afaiMax, mciMax, detectMask;

ee.Algorithms.If(hasData, 
  function() {
    // Compute indices for each image
    var afaiCollection = olciCollection.map(computeAFAI);
    var mciCollection = olciCollection.map(computeMCI);
    
    // Create daily composites (max values)
    afaiMax = afaiCollection.max().clip(roi);
    mciMax = mciCollection.max().clip(roi);
    
    // Apply thresholds for detection
    var afaiDetect = afaiMax.gte(AFAI_THRESHOLD);
    var mciDetect = mciMax.gte(MCI_THRESHOLD);
    
    // Union of detections
    detectMask = afaiDetect.or(mciDetect).rename('detect');
    
    return ee.Dictionary({
      'afaiMax': afaiMax,
      'mciMax': mciMax,
      'detectMask': detectMask
    });
  },
  function() {
    // No data case - create empty images
    var emptyImage = ee.Image(0).clip(roi);
    return ee.Dictionary({
      'afaiMax': emptyImage.rename('afai'),
      'mciMax': emptyImage.rename('mci'),
      'detectMask': emptyImage.rename('detect')
    });
  }
);

// Get results
var results = ee.Algorithms.If(hasData, 
  function() {
    var afaiCollection = olciCollection.map(computeAFAI);
    var mciCollection = olciCollection.map(computeMCI);
    
    var afaiMaxImg = afaiCollection.max().clip(roi);
    var mciMaxImg = mciCollection.max().clip(roi);
    
    var afaiDetect = afaiMaxImg.gte(AFAI_THRESHOLD);
    var mciDetect = mciMaxImg.gte(MCI_THRESHOLD);
    var detectMaskImg = afaiDetect.or(mciDetect).rename('detect');
    
    return [afaiMaxImg, mciMaxImg, detectMaskImg];
  },
  function() {
    var emptyImage = ee.Image(0).clip(roi);
    return [
      emptyImage.rename('afai'),
      emptyImage.rename('mci'),
      emptyImage.rename('detect')
    ];
  }
);

afaiMax = ee.Image(ee.List(results).get(0));
mciMax = ee.Image(ee.List(results).get(1));
detectMask = ee.Image(ee.List(results).get(2));

// ========================================
// VISUALIZATION
// ========================================

// Add layers to map for visual QA
Map.centerObject(roi, 7);
Map.addLayer(roi, {color: 'blue'}, 'Ghana 20nm Offshore Band', false);

// AFAI visualization
var afaiVis = {
  min: -0.005,
  max: 0.05,
  palette: ['blue', 'cyan', 'yellow', 'orange', 'red']
};
Map.addLayer(afaiMax, afaiVis, 'AFAI Max', false);

// MCI visualization
var mciVis = {
  min: -0.005,
  max: 0.02,
  palette: ['purple', 'blue', 'green', 'yellow', 'red']
};
Map.addLayer(mciMax, mciVis, 'MCI Max', false);

// Detection visualization
var detectVis = {
  min: 0,
  max: 1,
  palette: ['transparent', 'red']
};
Map.addLayer(detectMask, detectVis, 'Sargassum Detections');

print('Added visualization layers to map');

// ========================================
// EXPORT RASTERS
// ========================================

// Format date for file naming
var dateStr = TARGET_DATE;

// Export AFAI max
Export.image.toCloudStorage({
  image: afaiMax,
  description: 'AFAI_Max_' + dateStr,
  bucket: GCS_BUCKET,
  fileNamePrefix: 'sargassum/olci/afai_max_' + dateStr,
  region: roi,
  scale: EXPORT_SCALE,
  maxPixels: 1e9,
  formatOptions: {
    cloudOptimized: true
  }
});

// Export MCI max
Export.image.toCloudStorage({
  image: mciMax,
  description: 'MCI_Max_' + dateStr,
  bucket: GCS_BUCKET,
  fileNamePrefix: 'sargassum/olci/mci_max_' + dateStr,
  region: roi,
  scale: EXPORT_SCALE,
  maxPixels: 1e9,
  formatOptions: {
    cloudOptimized: true
  }
});

// Export detection mask
Export.image.toCloudStorage({
  image: detectMask,
  description: 'Detect_Mask_' + dateStr,
  bucket: GCS_BUCKET,
  fileNamePrefix: 'sargassum/olci/detect_' + dateStr,
  region: roi,
  scale: EXPORT_SCALE,
  maxPixels: 1e9,
  formatOptions: {
    cloudOptimized: true
  }
});

print('Created GeoTIFF export tasks');

// ========================================
// EXPORT DETECTION CENTROIDS
// ========================================

// Convert detection pixels to vectors (centroids)
var detectionVectors = detectMask.select('detect').selfMask()
  .reduceToVectors({
    geometry: roi,
    scale: EXPORT_SCALE,
    maxPixels: 1e9,
    geometryType: 'centroid',
    eightConnected: false
  });

// Add date property
detectionVectors = detectionVectors.map(function(feature) {
  return feature.set('date', TARGET_DATE);
});

print('Detection centroids:', detectionVectors.size());

// Export detection centroids
Export.table.toCloudStorage({
  collection: detectionVectors,
  description: 'Detection_Centroids_' + dateStr,
  bucket: GCS_BUCKET,
  fileNamePrefix: 'sargassum/olci/centroids_' + dateStr,
  fileFormat: 'GeoJSON'
});

print('Created detection centroids export task');

// ========================================
// SUMMARY
// ========================================

print('=== EXPORT SUMMARY ===');
print('Date:', TARGET_DATE);
print('AFAI threshold:', AFAI_THRESHOLD);
print('MCI threshold:', MCI_THRESHOLD);
print('Export scale:', EXPORT_SCALE, 'm');
print('GCS bucket:', GCS_BUCKET);
print('======================');

print('Check Tasks tab to monitor export progress');
print('Exports will be saved to: gs://' + GCS_BUCKET + '/sargassum/olci/');

// Final check
print('Script completed successfully');
print('Review map layers for visual QA before running exports');